import type { PermissionId, SystemRole } from '../../types';

/** Default permission matrix used by the client until org overrides load. */
export const ROLE_PERMISSIONS: Record<SystemRole, readonly PermissionId[]> = {
  super_admin: [
    'dashboard.view',
    'customers.create',
    'customers.read',
    'customers.update',
    'customers.delete',
    'vehicles.create',
    'vehicles.read',
    'vehicles.update',
    'vehicles.scan',
    'job_cards.create',
    'job_cards.read',
    'job_cards.update',
    'job_cards.transition',
    'job_cards.assign',
    'estimates.manage',
    'estimates.approve',
    'inventory.manage',
    'inventory.read',
    'billing.manage',
    'billing.read',
    'employees.manage',
    'employees.read',
    'attendance.manage',
    'attendance.self',
    'payroll.manage',
    'payroll.read',
    'reports.view',
    'reports.export',
    'documents.manage',
    'notifications.manage',
    'branches.manage',
    'rbac.manage',
    'settings.manage',
  ],
  owner: [
    'dashboard.view',
    'customers.create',
    'customers.read',
    'customers.update',
    'customers.delete',
    'vehicles.create',
    'vehicles.read',
    'vehicles.update',
    'vehicles.scan',
    'job_cards.create',
    'job_cards.read',
    'job_cards.update',
    'job_cards.transition',
    'job_cards.assign',
    'estimates.manage',
    'estimates.approve',
    'inventory.manage',
    'inventory.read',
    'billing.manage',
    'billing.read',
    'employees.manage',
    'employees.read',
    'attendance.manage',
    'attendance.self',
    'payroll.manage',
    'payroll.read',
    'reports.view',
    'reports.export',
    'documents.manage',
    'notifications.manage',
    'branches.manage',
    'rbac.manage',
    'settings.manage',
  ],
  branch_manager: [
    'dashboard.view',
    'customers.create',
    'customers.read',
    'customers.update',
    'vehicles.create',
    'vehicles.read',
    'vehicles.update',
    'vehicles.scan',
    'job_cards.create',
    'job_cards.read',
    'job_cards.update',
    'job_cards.transition',
    'job_cards.assign',
    'estimates.manage',
    'estimates.approve',
    'inventory.read',
    'inventory.manage',
    'billing.read',
    'billing.manage',
    'employees.read',
    'attendance.manage',
    'reports.view',
    'reports.export',
    'documents.manage',
  ],
  service_advisor: [
    'dashboard.view',
    'customers.create',
    'customers.read',
    'customers.update',
    'vehicles.create',
    'vehicles.read',
    'vehicles.update',
    'vehicles.scan',
    'job_cards.create',
    'job_cards.read',
    'job_cards.update',
    'job_cards.transition',
    'job_cards.assign',
    'estimates.manage',
    'estimates.approve',
    'inventory.read',
    'billing.read',
    'documents.manage',
  ],
  technician: [
    'dashboard.view',
    'job_cards.read',
    'job_cards.update',
    'job_cards.transition',
    'vehicles.read',
    'inventory.read',
    'documents.manage',
    'attendance.self',
  ],
  accountant: [
    'dashboard.view',
    'customers.read',
    'billing.manage',
    'billing.read',
    'estimates.manage',
    'reports.view',
    'reports.export',
    'payroll.read',
  ],
  store_manager: [
    'dashboard.view',
    'inventory.manage',
    'inventory.read',
    'job_cards.read',
    'reports.view',
  ],
  hr_manager: [
    'dashboard.view',
    'employees.manage',
    'employees.read',
    'attendance.manage',
    'payroll.manage',
    'payroll.read',
    'reports.view',
    'reports.export',
  ],
  receptionist: [
    'dashboard.view',
    'customers.create',
    'customers.read',
    'vehicles.create',
    'vehicles.read',
    'vehicles.scan',
    'job_cards.create',
    'job_cards.read',
    'attendance.self',
  ],
  customer: [
    'vehicles.read',
    'job_cards.read',
    'estimates.approve',
    'billing.read',
    'documents.manage',
  ],
};

export function permissionsForRoles(roles: SystemRole[]): PermissionId[] {
  const set = new Set<PermissionId>();
  for (const role of roles) {
    for (const permission of ROLE_PERMISSIONS[role] ?? []) {
      set.add(permission);
    }
  }
  return [...set];
}

export function can(
  permissions: readonly PermissionId[],
  required: PermissionId | PermissionId[],
): boolean {
  const needed = Array.isArray(required) ? required : [required];
  return needed.every((p) => permissions.includes(p));
}
