-- Global Indian vehicle catalog + workshop vehicle_focus (2W / 4W / both).

alter table public.organizations
  add column if not exists vehicle_focus text not null default 'both';

do $$ begin
  alter table public.organizations drop constraint if exists organizations_vehicle_focus_check;
exception when undefined_object then null;
end $$;

alter table public.organizations
  add constraint organizations_vehicle_focus_check
  check (vehicle_focus in ('two_wheeler', 'four_wheeler', 'both'));

create table if not exists public.vehicle_catalog_makes (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  category text not null check (category in ('two_wheeler', 'four_wheeler', 'both')),
  country text not null default 'IN',
  sort_order int not null default 100,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.vehicle_catalog_models (
  id uuid primary key default gen_random_uuid(),
  make_id uuid not null references public.vehicle_catalog_makes (id) on delete cascade,
  name text not null,
  category text not null check (category in ('two_wheeler', 'four_wheeler')),
  vehicle_type text not null,
  default_fuel_type text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (make_id, name)
);

create index if not exists vehicle_catalog_models_make_idx on public.vehicle_catalog_models (make_id);
create index if not exists vehicle_catalog_models_category_idx on public.vehicle_catalog_models (category);

alter table public.vehicle_catalog_makes enable row level security;
alter table public.vehicle_catalog_models enable row level security;

drop policy if exists "vehicle_catalog_makes_read" on public.vehicle_catalog_makes;
create policy "vehicle_catalog_makes_read"
  on public.vehicle_catalog_makes for select to authenticated using (true);

drop policy if exists "vehicle_catalog_models_read" on public.vehicle_catalog_models;
create policy "vehicle_catalog_models_read"
  on public.vehicle_catalog_models for select to authenticated using (true);

-- Seed makes
insert into public.vehicle_catalog_makes (name, category, country) values ('Maruti Suzuki', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Hyundai', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Tata', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Mahindra', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Toyota', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Kia', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Honda Cars', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('MG Motor', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Skoda', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Volkswagen', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Renault', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Nissan', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Citroën', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Jeep', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('BYD', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Force Motors', 'four_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Hero', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Honda Motorcycle', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('TVS', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Bajaj', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Royal Enfield', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Yamaha', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Suzuki Motorcycle', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('KTM', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Ola Electric', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Ather', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Jawa', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Triumph', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;
insert into public.vehicle_catalog_makes (name, category, country) values ('Harley-Davidson', 'two_wheeler', 'IN') on conflict (name) do update set category = excluded.category, is_active = true;

-- Seed models
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Alto K10', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'WagonR', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Celerio', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Swift', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Dzire', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Baleno', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Brezza', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Fronx', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Grand Vitara', 'four_wheeler', 'suv', 'hybrid' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Ertiga', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'XL6', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Jimny', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Invicto', 'four_wheeler', 'suv', 'hybrid' from public.vehicle_catalog_makes where name = 'Maruti Suzuki' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Grand i10 Nios', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'i20', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Aura', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Verna', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Exter', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Venue', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Creta', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Alcazar', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Tucson', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Ioniq 5', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'Hyundai' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Tiago', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Tigor', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Altroz', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Punch', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Nexon', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Nexon EV', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Curvv', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Harrier', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Safari', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Tata' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Bolero', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Bolero Neo', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Thar', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Scorpio Classic', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Scorpio-N', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'XUV3XO', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'XUV700', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'XUV400', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'BE 6e', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'XEV 9e', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'Mahindra' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Glanza', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Urban Cruiser Taisor', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Innova Crysta', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Innova Hycross', 'four_wheeler', 'suv', 'hybrid' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Fortuner', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Hilux', 'four_wheeler', 'commercial', 'diesel' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Camry', 'four_wheeler', 'car', 'hybrid' from public.vehicle_catalog_makes where name = 'Toyota' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Sonet', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Kia' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Seltos', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Kia' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Syros', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Kia' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Carens', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Kia' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Carnival', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Kia' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'EV6', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'Kia' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Amaze', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Cars' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'City', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Cars' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Elevate', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Cars' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Comet EV', 'four_wheeler', 'car', 'ev' from public.vehicle_catalog_makes where name = 'MG Motor' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Astor', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'MG Motor' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Hector', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'MG Motor' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'ZS EV', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'MG Motor' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Windsor EV', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'MG Motor' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Kylaq', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Skoda' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Kushaq', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Skoda' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Slavia', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Skoda' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Taigun', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Volkswagen' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Virtus', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Volkswagen' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Kwid', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Renault' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Triber', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Renault' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Kiger', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Renault' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Magnite', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Nissan' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'C3', 'four_wheeler', 'car', 'petrol' from public.vehicle_catalog_makes where name = 'Citroën' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Basalt', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Citroën' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Aircross', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Citroën' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Compass', 'four_wheeler', 'suv', 'petrol' from public.vehicle_catalog_makes where name = 'Jeep' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Meridian', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Jeep' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Atto 3', 'four_wheeler', 'suv', 'ev' from public.vehicle_catalog_makes where name = 'BYD' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Seal', 'four_wheeler', 'car', 'ev' from public.vehicle_catalog_makes where name = 'BYD' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Gurkha', 'four_wheeler', 'suv', 'diesel' from public.vehicle_catalog_makes where name = 'Force Motors' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Traveller', 'four_wheeler', 'commercial', 'diesel' from public.vehicle_catalog_makes where name = 'Force Motors' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'HF Deluxe', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Splendor Plus', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Passion Pro', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Glamour', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Xtreme 160R', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Xpulse 200', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Pleasure+', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Destini 125', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Hero' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Shine', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'SP 125', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Unicorn', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Hornet 2.0', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'CB350', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Activa 6G', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Activa 125', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Dio', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Honda Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Raider 125', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Apache RTR 160', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Apache RTR 200', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Apache RR 310', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Ronin', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Jupiter', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Ntorq 125', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'iQube', 'two_wheeler', 'scooter', 'ev' from public.vehicle_catalog_makes where name = 'TVS' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'CT 100', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Platina', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Pulsar 150', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Pulsar N160', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Pulsar NS200', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Dominar 400', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Avenger', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Chetak', 'two_wheeler', 'scooter', 'ev' from public.vehicle_catalog_makes where name = 'Bajaj' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Hunter 350', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Classic 350', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Meteor 350', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Bullet 350', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Himalayan 450', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Guerrilla 450', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Super Meteor 650', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Interceptor 650', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Royal Enfield' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'FZ-S', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Yamaha' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'MT-15', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Yamaha' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'R15 V4', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Yamaha' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Fascino 125', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Yamaha' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Aerox 155', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Yamaha' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Gixxer SF', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Suzuki Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Access 125', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Suzuki Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Avenis', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Suzuki Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Burgman Street', 'two_wheeler', 'scooter', 'petrol' from public.vehicle_catalog_makes where name = 'Suzuki Motorcycle' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, '200 Duke', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'KTM' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, '250 Duke', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'KTM' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, '390 Duke', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'KTM' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, '390 Adventure', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'KTM' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'S1 Air', 'two_wheeler', 'scooter', 'ev' from public.vehicle_catalog_makes where name = 'Ola Electric' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'S1 Pro', 'two_wheeler', 'scooter', 'ev' from public.vehicle_catalog_makes where name = 'Ola Electric' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Roadster', 'two_wheeler', 'bike', 'ev' from public.vehicle_catalog_makes where name = 'Ola Electric' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, '450X', 'two_wheeler', 'scooter', 'ev' from public.vehicle_catalog_makes where name = 'Ather' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Rizta', 'two_wheeler', 'scooter', 'ev' from public.vehicle_catalog_makes where name = 'Ather' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, '42', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Jawa' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Perak', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Jawa' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Speed 400', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Triumph' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'Scrambler 400 X', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Triumph' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;
insert into public.vehicle_catalog_models (make_id, name, category, vehicle_type, default_fuel_type) select id, 'X440', 'two_wheeler', 'bike', 'petrol' from public.vehicle_catalog_makes where name = 'Harley-Davidson' on conflict (make_id, name) do update set category = excluded.category, vehicle_type = excluded.vehicle_type, default_fuel_type = excluded.default_fuel_type, is_active = true;

create or replace function public.set_workshop_vehicle_focus(p_focus text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_org uuid;
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if p_focus not in ('two_wheeler', 'four_wheeler', 'both') then
    raise exception 'Invalid vehicle focus';
  end if;
  select preferred_organization_id into v_org from public.profiles where id = v_user;
  if v_org is null then
    select organization_id into v_org from public.user_roles
    where user_id = v_user and is_active = true order by created_at limit 1;
  end if;
  if v_org is null then raise exception 'No workshop'; end if;
  if not public.has_permission(v_org, 'settings.manage') then
    raise exception 'Not allowed';
  end if;
  update public.organizations set vehicle_focus = p_focus, updated_at = now() where id = v_org;
  return jsonb_build_object('organization_id', v_org, 'vehicle_focus', p_focus);
end;
$$;

revoke all on function public.set_workshop_vehicle_focus(text) from public;
grant execute on function public.set_workshop_vehicle_focus(text) to authenticated;

drop function if exists public.create_workshop(text, text, text, text, text, text, text, text);

create or replace function public.create_workshop(
  p_org_name text,
  p_branch_name text default 'Head Office',
  p_branch_code text default 'HO',
  p_gstin text default null,
  p_phone text default null,
  p_city text default null,
  p_state text default null,
  p_billing_email text default null,
  p_vehicle_focus text default 'both'
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid := auth.uid();
  v_org uuid;
  v_branch uuid;
  v_slug text;
  v_base text;
  v_focus text := coalesce(nullif(trim(p_vehicle_focus), ''), 'both');
begin
  if v_user is null then raise exception 'Not authenticated'; end if;
  if coalesce(nullif(trim(p_org_name), ''), '') = '' then raise exception 'Workshop name is required'; end if;
  if v_focus not in ('two_wheeler', 'four_wheeler', 'both') then v_focus := 'both'; end if;

  v_base := lower(regexp_replace(trim(p_org_name), '[^a-zA-Z0-9]+', '-', 'g'));
  v_base := trim(both '-' from v_base);
  if v_base = '' then v_base := 'workshop'; end if;
  v_slug := v_base || '-' || substr(replace(gen_random_uuid()::text, '-', ''), 1, 6);

  insert into public.organizations (
    name, legal_name, gstin, phone, city, state, country, currency, timezone, slug, plan, billing_email, vehicle_focus
  ) values (
    trim(p_org_name), trim(p_org_name),
    nullif(upper(trim(coalesce(p_gstin, ''))), ''),
    nullif(trim(coalesce(p_phone, '')), ''),
    nullif(trim(coalesce(p_city, '')), ''),
    nullif(trim(coalesce(p_state, '')), ''),
    'IN', 'INR', 'Asia/Kolkata', v_slug, 'starter',
    nullif(lower(trim(coalesce(p_billing_email, ''))), ''),
    v_focus
  ) returning id into v_org;

  insert into public.branches (organization_id, code, name, phone, city, state, gstin, is_head_office)
  values (
    v_org, coalesce(nullif(trim(p_branch_code), ''), 'HO'),
    coalesce(nullif(trim(p_branch_name), ''), 'Head Office'),
    nullif(trim(coalesce(p_phone, '')), ''),
    nullif(trim(coalesce(p_city, '')), ''),
    nullif(trim(coalesce(p_state, '')), ''),
    nullif(upper(trim(coalesce(p_gstin, ''))), ''),
    true
  ) returning id into v_branch;

  insert into public.branch_settings (branch_id) values (v_branch) on conflict (branch_id) do nothing;
  insert into public.user_roles (user_id, organization_id, branch_id, role_id, is_active)
  values (v_user, v_org, v_branch, 'owner', true);

  update public.profiles
  set preferred_organization_id = v_org, preferred_branch_id = v_branch, updated_at = now()
  where id = v_user;

  return jsonb_build_object(
    'organization_id', v_org, 'branch_id', v_branch, 'role_id', 'owner',
    'slug', v_slug, 'vehicle_focus', v_focus, 'created', true
  );
end;
$$;

revoke all on function public.create_workshop(text, text, text, text, text, text, text, text, text) from public;
grant execute on function public.create_workshop(text, text, text, text, text, text, text, text, text) to authenticated;
